### ISSUE TITLE
Highlight rectangle is wrong

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit#102] opened 2016-05-13 17:03 UTC
@samreid @arouinfar  getting three consistent errors that completely kill the sim, currently investigating why so stay tuned:
```
circuit-construction-kit-black-box_en.html:587
Error: <g> attribute transform: Expected number, "matrix(NaN,NaN,NaN,NaN,…".
i.update @ circuit-construction-kit-black-box_en.html:587
```
```
circuit-construction-kit-black-box_en.html:598 
Uncaught TypeError: Cannot read property 'width' of undefined
(no stack trace)
```
```
Error: <line> attribute x2: Expected length, "NaN".n.updateSVGSelf @ circuit-construction-kit-black-box_en.html:593
i.updateSVG @ circuit-construction-kit-black-box_en.html:590
i.update @ circuit-construction-kit-black-box_en.html:590
i.update @ circuit-construction-kit-black-box_en.html:587
i.update @ circuit-construction-kit-black-box_en.html:588
i.update @ circuit-construction-kit-black-box_en.html:587
i.update @ circuit-construction-kit-black-box_en.html:588
i.update @ circuit-construction-kit-black-box_en.html:587
i.update @ circuit-construction-kit-black-box_en.html:588
n.updateDisplay @ circuit-construction-kit-black-box_en.html:593
i.stepSimulation @ circuit-construction-kit-black-box_en.html:604
i.runAnimationLoop @ circuit-construction-kit-black-box_en.html:604
2circuit-construction-kit-black-box_en.html:587
```

**Comment by phet-steele** [comment] 2016-05-13 17:57
For the sake of me and @samreid  finding out what's happening, I'll document images and videos for these errors with no specific context (because I don't know the context :smile:):

![cckbb1](https://cloud.githubusercontent.com/assets/5863899/15256205/9ae75516-18fd-11e6-8a73-24047332c4f8.PNG)

![cckbb2](https://cloud.githubusercontent.com/assets/5863899/15256225/b9002870-18fd-11e6-8745-58d4838c993f.PNG)

![cckbb01](https://cloud.githubusercontent.com/assets/5863899/15256341/5dcf8cf6-18fe-11e6-87ed-38ae3088ff06.gif)

**Comment by samreid** [comment] 2016-05-18 20:14
I'm having difficulty reproducing this kind of problem, any suggestions @phet-steele?

**Comment by samreid** [comment] 2016-05-19 02:07
I fixed #103 which may have been related to this issue.  @phet-steele master is stable now and you could use it for testing to generate more helpful error messages.  I'll continue testing a bit, but if I can't find the problem I'll reassign it to you to continue testing in master.

**Comment by samreid** [comment] 2016-05-19 02:16
I also fixed #104.  I think the probability that #103 and #104 have addressed the issue discovered here is less than 10%, since the issue here looks related to undefined/NaN.  But I'm having trouble reproducing the issue.  @phet-steele can you pull and test from test-server so we get good error messages, and let me know if you see anything like this or any other issues that should be fixed before we share this sim to Stanford?

**Comment by samreid** [comment] 2016-05-19 04:56
@ariel-phet said @phet-steele has many things on his plate at the moment, and perhaps we could have Thursdays design meeting, discuss then, and have @arouinfar test and go from there.  Sounds good to me!

**Comment by arouinfar** [comment] 2016-05-19 15:55
👍

**Comment by samreid** [comment] 2016-05-20 03:17
After fixing all other "high-priority" issues in this repo, @arouinfar will test the sim and if all appears well we will deliver it to Stanford, hopefully within a week or so.

**Comment by samreid** [comment] 2016-05-29 22:51
@phet-steele can you offer guidance in reproducing this kind of problem?  Also, cck is now available on phet-test, so you may be able to get better error messages.

**Comment by phet-steele** [comment] 2016-06-06 19:48
@samreid I may have discovered how to do the second screenshot (the one with the bad yellow box).

Can't guarantee if this is the only way to make it happen, but check it out. BTW, this is 1.0.0-dev.15:

1. In build circuit mode, attach a component to a vertex
2. Rotate that same component
3. Click reveal
4. Click the component

![cckbb01](https://cloud.githubusercontent.com/assets/5863899/15835427/31d4ec48-2bed-11e6-90b5-4592a67a7efc.gif)

**Comment by samreid** [comment] 2016-06-13 20:23
Thanks @phet-steele, I was able to reproduce the problem you identified.

**Comment by samreid** [comment] 2016-06-13 20:44
It seems like FixedLengthCircuitElementNode.js is assuming elements get created at an angle of 0.  I'm not sure exactly where this assumption occurs though.

**Comment by samreid** [comment] 2016-06-13 20:51
In the above commit, the endVertex is set to an angle of zero, then the layout is performed, then the endVertex position is restored.  The behavior seems to be correct, however we must understand why this behavior is occurring and find a better solution.

**Comment by samreid** [comment] 2016-06-14 01:48
I'll close this issue with the workaround in place, then create a new issue focused on improving this.

**Closed by samreid** 2016-06-14 01:48 UTC
Labels: circuit-construction-kit:black-box-study, priority:2-high, type:bug
